package Grupo12.Projeto_ES;

import java.io.File;
import java.io.PrintWriter;
import java.awt.Desktop; 
import java.io.FileNotFoundException;


public class Html {
	public static void main(String[] args) {
		File file = new File("agenda.html");
		try {

		PrintWriter printWriter = new PrintWriter(file);
		String html = " <!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ " \r\n"
				+ "<body>\r\n"
				+ "    <h1>Horário</h1>\r\n"
				+ "    <table border=\"8\" cellspacing=\"0\" align=\"center\">\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\"\r\n"
				+ "                width=\"100\"><br>\r\n"
				+ "                <b>Hora/Dia</b></br>\r\n"
				+ "            </td>\r\n"
				+ "            <td align=\"center\" height=\"50\"\r\n"
				+ "                width=\"100\">\r\n"
				+ "                <b>Segunda</b>\r\n"
				+ "            </td>\r\n"
				+ "            <td align=\"center\" height=\"50\"\r\n"
				+ "                width=\"100\">\r\n"
				+ "                <b>Terça</b>\r\n"
				+ "            </td>\r\n"
				+ "            <td align=\"center\" height=\"50\"\r\n"
				+ "                width=\"100\">\r\n"
				+ "                <b>Quarta</b>\r\n"
				+ "            </td>\r\n"
				+ "            \r\n"
				+ "            <td align=\"center\" height=\"50\"\r\n"
				+ "                width=\"100\">\r\n"
				+ "                <b>Quinta</b>\r\n"
				+ "            </td>\r\n"
				+ "            <td align=\"center\" height=\"50\"\r\n"
				+ "                width=\"100\">\r\n"
				+ "                <b>Sexta</b>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>8:00-8:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            \r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>8:30-9:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>9:00-9:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>9:30-10:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>10:00-10:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>10:30-11:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>11:30-12:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>12:00-12:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>12:30-13:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>13:00-13:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>13:30-14:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>14:00-14:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>14:30-15:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>15:00-15:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>15:30-16:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>16:00-16:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>16:30-17:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>17:00-17:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>17:30-18:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>18:00-18:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>18:30-19:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>19:00-19:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>19:30-20:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>20:00-20:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>20:30-21:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>21:00-21:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>21:30-22:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>22:00-22:30</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "        <tr>\r\n"
				+ "            <td align=\"center\" height=\"50\">\r\n"
				+ "                <b>22:30-23:00</b></td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "            <td align=\"center\" height=\"50\">cadeira</td>\r\n"
				+ "        </tr>\r\n"
				+ "    </table>\r\n"
				+ "</body>\r\n"
				+ " \r\n"
				+ "</html>";

		printWriter.println(html);
		printWriter.close();

		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	     try  {
	       Desktop desktop = Desktop.getDesktop();
	        if(file.exists()) desktop.open(file);
	     }  
	        catch(Exception e)  
	        {  
	            e.printStackTrace();  
	        }  
	}
}


